const dataModel = require("../models/Data");

// Show all tasks
const getTask = async (req, res) => {
  const userID = req.cookies.userID;
  
  try {
    const tasks = await dataModel.find({ userID }).sort({ createdAt: -1 });
    res.status(200).json(tasks);
  } catch (error) {
    res.status(500).json({ message: "Error fetching tasks", error: error.message });
  }
};

// Add & save a new task
const saveTask = async (req, res) => {
  const { task } = req.body;
  const userID = req.cookies.userID;
  
  if (!task || task.trim() === "") {
    return res.status(400).json({ message: "Task content is required." });
  }

  try {
    const newTask = new dataModel({
      task,
      userID,
      completed: false
      // id will be auto-generated by the schema
    });

    await newTask.save();
    res.status(201).json(newTask);
  } catch (error) {
    res.status(500).json({ message: "Error saving task", error: error.message });
  }
};

// Update a task
const updateTask = async (req, res) => {
  const { task } = req.body;
  const { id } = req.params;
  
  if (!task || task.trim() === "") {
    return res.status(400).json({ message: "Task content is required." });
  }

  try {
    const updatedTask = await dataModel.findOneAndUpdate(
      { id },
      { task },
      { new: true }
    );
    
    if (!updatedTask) {
      return res.status(404).json({ message: "Task not found." });
    }
    
    res.status(200).json(updatedTask);
  } catch (error) {
    res.status(500).json({ message: "Error updating task", error: error.message });
  }
};

// Convert task content to uppercase
const upperCaseTask = async (req, res) => {
  const { id } = req.params;
  const { task } = req.body;
  
  if (!task || task.trim() === "") {
    return res.status(400).json({ message: "Task content is required." });
  }

  try {
    const updatedTask = await dataModel.findOneAndUpdate(
      { id },
      { task: task.toUpperCase() },
      { new: true }
    );
    
    if (!updatedTask) {
      return res.status(404).json({ message: "Task not found." });
    }
    
    res.status(200).json(updatedTask);
  } catch (error) {
    res.status(500).json({ message: "Error updating task", error: error.message });
  }
};

// Delete a task
const deleteTask = async (req, res) => {
  const { id } = req.params;

  try {
    const deletedTask = await dataModel.findOneAndDelete({ id });
    
    if (!deletedTask) {
      return res.status(404).json({ message: "Task not found." });
    }
    
    res.status(200).json({ message: "Task deleted successfully", task: deletedTask });
  } catch (error) {
    res.status(500).json({ message: "Error deleting task", error: error.message });
  }
};

// Mark task as completed or incomplete
const completedTask = async (req, res) => {
  const { id } = req.params;

  try {
    const task = await dataModel.findOne({ id });
    
    if (!task) {
      return res.status(404).json({ message: "Task not found." });
    }

    const updatedTask = await dataModel.findOneAndUpdate(
      { id },
      { completed: !task.completed },
      { new: true }
    );
    
    res.status(200).json(updatedTask);
  } catch (error) {
    res.status(500).json({ message: "Error updating completion status", error: error.message });
  }
};

module.exports = {
  getTask,
  saveTask,
  updateTask,
  upperCaseTask,
  deleteTask,
  completedTask
};